# BedBlock — настройки

# Ломать ли кровать при попытке сна (true) или просто запрещать сон (false)
break-bed: true

# Звук и частицы при срабатывании
effects: true

# Сообщение игроку (& для цветов)
message: '&cСпать в мире слишком опасно!'
